### PR TITLE
add CMakeLists.txt for total SPAdes

### PR DESCRIPTION
**Pull request by alienzj**

### CODE REVIEW

**Comment by asl** [comment]
What is the rationale for this patch?

**Comment by alienzj** [comment]
The total project can be parsed using IDE, like kdevelop or clion.

**Comment by alienzj** [comment]
Do you consider to merge it? If you won't, I will close it.
SPAdes is a great project, so many nice assemblers for genomic research.
Thanks very much~

**Comment by asl** [comment]
Frankly speaking, it does not make much sense – the project still could parsed now (and this is what we're using all the time). Also, there are some issues with the PR as-is, e.g. commented out checks, etc.

**Pull request closed without merging**
